front-end/app/studio/pages/apis/newapi/newapi.page.html
front-end/app/studio/pages/login/login.page.html
front-end/app/studio/services/apis-local.service.ts

Tiny change but it was catching my eye 😄

Change Github to GitHub

---

README.md

Fixed code blocks in README.md, bash code is better looking now.

Fixed code blocks in README.md

---

distro/openshift/apicurio-template.yml

Parametrizable limits on the Openshift Deployment Configs

Set limits on Openshift Deployment Configs

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/master.component.ts

Stop context menu disappearing on macOS

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/config/HubConfiguration.java

fix for
https://github.com/Apicurio/apicurio-studio/issues/466
Add page handling to GitLabConnector to fetch until response size is under the perPage number.
Also added some environment variable to make the group fecthing configurable.
Also can be related to :
https://github.com/Apicurio/apicurio-studio/issues/395

Apicurio studio 466

---

README.md

Hi. Here's a quick patch for #639.

Updating readme for #639

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/schema-type-editor.component.ts

@EricWittmann Hi, this is a WIP, I couldn't figure out how to propagate the "file" type into the OpenAPI model. The use and processing of the `SimplifiedType` is not very clear to me atm.

Support "file" as an option for OpenAPI 2 form body parameters

---

front-end/studio/src/app/components/common/drop-down.component.ts
front-end/studio/src/app/editor.module.ts
front-end/studio/src/app/pages/apis/create/_components/create-form.component.ts
front-end/studio/src/app/pages/apis/import/_components/import-form.component.ts
front-end/studio/src/app/pages/apis/{apiId}/_components/generate-project.wizard.ts
front-end/studio/src/app/pages/apis/{apiId}/collaboration/api-collaboration.page.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/add-media-type.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/add-response.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/add-response.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/clone-response.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/clone-response.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/editors/parameter-editor.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/editors/property-editor.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/formData-param-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/requestBody-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/responses-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/responses-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/header-param-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/query-param-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/schema-type-editor.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_services/httpcode.service.ts
front-end/studio/src/app/pages/apis/{apiId}/publish/_components/bitbucket-resource.component.ts
front-end/studio/src/app/pages/apis/{apiId}/publish/_components/github-resource.component.ts
front-end/studio/src/app/pages/apis/{apiId}/publish/_components/gitlab-resource.component.ts
front-end/studio/src/app/pages/apis/{apiId}/publish/publish.page.ts
front-end/studio/src/app/pages/settings/validation/_components/profile-editor.component.ts

Merge after https://github.com/Apicurio/oai-ts-commands/pull/46
@EricWittmann Hey, there is an issue I couldn't yet solve - if you clone a response in UI, 
everything works OK, but if you reload the page, the content of the cloned response
is missing, e.g. the description is null. Any advice?
There is also another minor problem, when you create/clone a response and switch to its tab,
after hitting "undo", the tab disappears, but the UI does not switch to another one.
The simple solution for the delete action does not seem to directly applicable.
There are also some minor code improvements, that can be separated out if need be.

Implement "Clone Response" action

---

distro/openshift/auth/Dockerfile
distro/openshift/auth/auth-entrypoint.sh
distro/quickstart/src/main/resources/standalone/configuration/standalone-apicurio.xml
front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/filters/BaseHrefFilter.java
pom.xml

Hey @asheliahut - if you'd like to take a quick look at the changes in this PR and provide any feedback you may have, that'd be great. :)  I think everything is working fine, but another set of eyes would be great.

Upgrade to Keycloak 7

---

front-end/studio/src/app/components/common/ace-editor.component.ts
front-end/studio/src/app/components/common/code-editor.component.ts
front-end/studio/src/app/pages/apis/create/create.page.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/graphql-editor.component.ts
front-end/studio/src/app/services/template.service.ts

Allow syntax highlighting thru Ace editor build-in gql support. 
```
APICURIO_UI_FEATURE_GRAPHQL=true ./distro/quickstart/target/apicurio-studio-*-SNAPSHOT/bin/standalone.sh -c standalone-apicurio.xml
```
See demo video with the changes:
https://youtu.be/VXNPiPioMwk

Add syntax highlighting to graphql editor

---

pom.xml

Error generating javadocs with JDK 13 #1091

---

distro/kubernetes/README.md

Fixed typo in Kubernetes installation documentation

---

distro/kubernetes/README.md
distro/kubernetes/apicurio-configmap.yaml
distro/kubernetes/apicurio-studio-ingresses.yaml

Signed-off-by: Cem Nura <cem.nura@gmail.com>

Configured WS pod to be exposed via Ingress

---

distro/helm/.helmignore
distro/helm/Chart.yaml
distro/helm/README.md
distro/helm/templates/NOTES.txt
distro/helm/templates/apicurio-secrets.yaml
distro/helm/templates/apicurio-studio-api-deployment.yaml
distro/helm/templates/apicurio-studio-db-deployment.yaml
distro/helm/templates/apicurio-studio-ingresses.yaml
distro/helm/templates/apicurio-studio-services.yaml
distro/helm/templates/apicurio-studio-ui-deployment.yaml
distro/helm/templates/apicurio-studio-ws-deployment.yaml
distro/helm/templates/mysql-apicurio-persistentvolumeclaim.yaml
distro/helm/values.yaml

Hi team 
I wrote initial helm 3 installation. I was able to test it locally only by rendering 
> helm template apicurio .
Had some issues to pull remote images to my minikube cluster therefore kindly asking if you can try this installation to any of your k8s clusters. My intention is to build upon this and apply to openshift 3.11 as we do for any other helm k8s installation. Happy to get feedback

init helm installation

---

distro/kubernetes/apicurio-studio-ingresses.yaml

Pull Request for ingress as the subPath /ws is not supported anymore.
@EricWittmann i'll have a look into a k8s-operator for that now.
laterz

add kubernetes config changes

---

front-end/studio/src/app/services/template.service.ts

Hi! 
This is a PR that adds a template API for AsyncAPI 2.0 specification. It is based on the `User signed-up API` that is exposed into AsyncAPI tutorials.

Adding an API template for AsyncAPI 2.0

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/ValidationProfilesResource.java
back-end/hub-api/src/test/java/io/apicurio/hub/api/connectors/HttpClientTest.java
back-end/hub-api/src/test/java/io/apicurio/hub/api/content/AbsoluteReferenceResolverTest.java
back-end/hub-api/src/test/java/test/io/apicurio/hub/api/MockHttpServletRequest.java
back-end/hub-api/src/test/java/test/io/apicurio/hub/api/MockStorage.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/storage/jdbc/JdbcStorage.java
front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/filters/KeycloakAuthenticationFilter.java
platforms/quarkus/api/pom.xml
platforms/quarkus/api/src/main/java/io/apicurio/hub/api/quarkus/StudioApiQuarkusMain.java
platforms/quarkus/api/src/main/java/io/apicurio/hub/api/security/QuarkusLinkedAccountsProvider.java
platforms/quarkus/ui/pom.xml
platforms/quarkus/ws/src/main/java/io/apicurio/hub/ws/quarkus/StudioWsQuarkusMain.java
platforms/quarkus/ws/src/main/resources/application.properties
test/integration/arquillian/pom.xml
test/integration/arquillian/src/test/java/io/apicurio/test/integration/arquillian/helpers/TestOperationHelper.java
test/integration/single-node-keycloak/pom.xml
test/integration/single-node-keycloak/src/test/java/io/apicurio/test/integration/arquillian/KeycloakSetupTestIT.java

Hey @carlesarnal can you have a look at this?  Maybe build locally and run using docker compose to make sure the addition of the Main quarkus class I added didn't mess anything up?

Added quarkus main classes and fixed some warnings

---

pom.xml

Hello, 
This PR is related to https://github.com/Apicurio/apicurio-studio/issues/1506, it's been through my corp CI and fixes our connection issue. 
Afaik no problem appeared on classic create/edit/delete operations on designs and during editing sessions.

Update postgresql dependency to 42.2.20

---

pom.xml

See [this](https://bugs.mysql.com/bug.php?id=102435) for more information.

Revert mysql driver version to 22

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.ts

Hello,
this PR adding maximum, minimum, maxLength, minlength, pattern ( OAS 3 imported types from JSON Schema )
The next part is coming soon.
See : https://github.com/Apicurio/apicurio-studio/issues/1193
Have a good day.

adding maximum, minimum, maxLength,minlength, pattern oas3 types

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksConnector.java

Straight forward, as suggested.
There is no test setup for the MicrocksConnector however, so adding tests seems to be a whole other level of effort.
Fixes #1533

Run dereferencer before sending spec to Microcks

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/property-row.component.ts

add Example into properties section (UX)

add Example into properties section (UX)

---

front-end/studio/src/app/components/common/data-table.component.css
front-end/studio/src/app/components/common/data-table.component.html
front-end/studio/src/app/components/common/data-table.component.ts

Implement select all in data-table component when allowSelectAll = true

chore: Implement select all in data-table component.

---

distro/kubernetes/apicurio-studio-api-deployment.yaml

chore: fix a typo

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/security/KeycloakAuthenticationFilter.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/security/QuarkusAuthenticationFilter.java
front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/filters/KeycloakAuthenticationFilter.java
front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/filters/QuarkusAuthenticationFilter.java

Follow up for #1679, adds null safety for realms with no default roles

---

DEV_MODE.md
back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabResourceResolver.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java

Fixes #1729
This fixes 3 issues I found in the gitlab publication flow, more details in the issue

Make the gitlab publication flow properly handle space/% in file names and slashes in branch names

---

front-end/studio/src/app/components/common/activity-item.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/enum-payload-tab.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/message-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/payload-tab.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/oneof-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/oneof-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/message-form.component.html

Adding change/update reference in messages(oneOf) from an operation
Warning : depends on https://github.com/Apicurio/apicurio-data-models/pull/364
n

update messages/oneOf/reference OK from operations

---

distro/helm/templates/NOTES.txt
distro/helm/templates/_helpers.tpl
distro/helm/templates/apicurio-secrets.yaml
distro/helm/templates/apicurio-studio-api-deployment.yaml
distro/helm/templates/apicurio-studio-db-deployment.yaml
distro/helm/templates/apicurio-studio-ingresses.yaml
distro/helm/templates/apicurio-studio-ui-deployment.yaml
distro/helm/templates/apicurio-studio-ws-deployment.yaml
distro/helm/templates/mysql-apicurio-persistentvolumeclaim.yaml
distro/helm/values.yaml

Added improvements to the helm chart:
- Fixed a typo in the notes
- Added being able to use external db instead of installing one with chart
- Added ingress annotation and tls configuration
- Added deployment resource configuration
- Added being able to use an existing secret instead of creating a new one

Helm chart improvements

---

front-end/studio/src/app/pages/apis/{apiId}/editor/aaieditor.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/editor.component.ts

This change will add support to pass in a list of validation extensions
into the editor components. For validation the editors will use the
new Library#validateModel method which support backward
compatibility for default validation.

Add support for validation extensions in editors

---

.github/workflows/release-images.yaml
.github/workflows/release.yaml
.github/workflows/update-website.yaml
.github/workflows/verify.yaml

- Build and publish multi-arch images
- decouple release workflow
- push snaphot images

Multiarch images

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/properties-section.component.ts

PROPERTIES is now defined under "Inheritance Type"

---

platforms/quarkus/ui/src/main/resources/application.properties

Hello @EricWittmann ,
The recent modification about CORS seems to be missing something. 
I have just copy what you write in the API config and add it to the UI config. 
It solves this problem for me :

CORS config for UI

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_util/model.util.ts

Hello, 
I saw the issue #1887. 
The issue is about using the defined properties rules in the exemple generated. 
I tried to add something to ExampleGenerator for that. 
What is different : the password, string, boolean and integer are generated randomly using the defined rules.
What do you think about this ?

Add example generator

---

back-end/hub-api/pom.xml
back-end/hub-api/src/main/java/io/apicurio/hub/api/bitbucket/BitbucketSourceConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/connectors/AbstractSourceConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/github/GitHubSourceConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/HubApplication.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/security/GitHubAuthenticationFilter.java
back-end/hub-api/src/test/java/io/apicurio/hub/api/bitbucket/BitbucketSourceConnectorTest.java
back-end/hub-api/src/test/java/io/apicurio/hub/api/connectors/HttpClientTest.java
back-end/hub-core/pom.xml
front-end/servlet/pom.xml
front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/filters/GitHubAuthenticationFilter.java
pom.xml
tools/release/pom.xml
tools/release/src/main/java/io/apicurio/studio/tools/release/ReleaseTool.java

Upgrade unirest version to 3.14.1. Solves issue #309

chore: upgrade unirest version to 3.14.1

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/aaimain-form.component.html

Hello @EricWittmann, 
Just a very little change to add tag section in the async API editor. 
Is it ok ? :smiley:

Add tag section for Async API

---

platforms/quarkus/ui/src/main/resources/application.properties

Hello, 
I think this modification correct the issue #2188.
Is it ok ? :smiley:

Update quarkus token refresh

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_util/model.util.ts

Hello, 
Here is two modifications on example generation : 
- Fix example bug when the string properties have no "maxLenght" attribute  -> Random length 
- When there is an "AllOf" inheritance, inherited properties are added to the generated example

Example : fix bug string without maxLenght + add AllOf
