Apicurio/apicurio-studio

.dockerignore
Dockerfile
Makefile

This Adds a Dockerfile for container image generation and a Makefile to operate the image. ```make help``` provides help for the Makefile targets.
Please feel free to change the docker registry namespace. I was using my personal namespace (maneta) for  to test the deployment. 
The requirements to run this are:
* GNU Make
* Docker

Adding Docker Generation Files

---

Dockerfile
Makefile

In this PR we introduce the possibility to deploy local or remote release to the docker registry

Introducing Local/Remote release deployments

---

distro/quickstart/pom.xml
distro/quickstart/src/main/assembly/quickstart.xml

This reduce a build time and use maven cache for builds.
Also shell permissions inside quickstart also fixed.
Please review.

Able to download WildFly and KeCloak adapter with maven

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/common/context-help.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/common/context-help.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/editor.component.css

- when info box extends below bottom of window user can now scroll the window to see entire contents
- removed `left` and `right` properties from the `ContextHelpComponent`
- info box positioning is all  done in the css now

Fixes Syndesis Issue 3497: Apicurio GUI - info box not showed properly

---

front-end/studio/src/app/pages/apis/{apiId}/editor/editor.component.ts

Want to do a bit more testing on this first before merging, but had a couple of questions (inline)

Add macOS shortcuts for undo/redo

---

distro/openshift/apicurio-auth-template.yml
distro/openshift/apicurio-postgres-template.yml
distro/openshift/apicurio-standalone-template.yml

Adding split templates:
- postgresql
- auth
- studio (ui + ws + api)
I was originally just splitting  the auth one (keycloak) but it turns out that we neeed to deploy postgre first so I created a postgre template as well.
The "full featured" template still exists, this change is being made based on this issue comments: #485

openshift templates

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/IMicrocksConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksConnector.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksConnectorException.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksImporter.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksSecret.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/microcks/MicrocksSecretRef.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/IDesignsResource.java
back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/DesignsResource.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/beans/ApiContentType.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/config/HubConfiguration.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/storage/jdbc/CommonSqlStatements.java
front-end/studio/src/app/app-routing.module.ts
front-end/studio/src/app/app.module.ts
front-end/studio/src/app/components/common/activity-item.component.ts
front-end/studio/src/app/models/mock-api.model.ts
front-end/studio/src/app/pages/apis/{apiId}/api-detail.page.html
front-end/studio/src/app/pages/apis/{apiId}/mock/mock.page.css
front-end/studio/src/app/pages/apis/{apiId}/mock/mock.page.html
front-end/studio/src/app/pages/apis/{apiId}/mock/mock.page.ts
front-end/studio/src/app/services/apis.service.ts

This is for #369 ;-) 
Within this commit:
* Adding new MicrocksConnector configured with HubConfig
* Adding new API on back-end with front-end client API
* Adding front-end action menu
* Adding persistence of api_content for each mock publication
* Adding activity into API feed on summary page

Mock with Microcks action support

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java

solve the garbled problem when publish to gitlab

encoding request body with utf8 when commit to gitlab

---

front-end/studio/src/app/components/common/activity-item.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/header-param-row.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/header-param-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/header-param-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/path-param-row.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/path-param-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/path-param-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/query-param-row.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/query-param-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/query-param-row.component.ts
pom.xml

This commit adds examples management for `path`, `query` and `header` parameters.
It requires updating dependencies to `apicurio-data-models:1.0.8-SNAPSHOT` once https://github.com/Apicurio/apicurio-data-models/pull/49 will be accepted and merge (this later PR adds necessary commands for adding/updating/removing example to a parameter).

Adding parameters examples management

---

distro/kubernetes/README.md
distro/kubernetes/apicurio-configmap.yaml
distro/kubernetes/apicurio-secrets.yaml
distro/kubernetes/apicurio-studio-api-deployment.yaml
distro/kubernetes/apicurio-studio-db-deployment.yaml
distro/kubernetes/apicurio-studio-ingresses.yaml
distro/kubernetes/apicurio-studio-services.yaml
distro/kubernetes/apicurio-studio-ui-deployment.yaml
distro/kubernetes/apicurio-studio-ws-deployment.yaml
distro/kubernetes/mysql-apicurio-persistentvolumeclaim.yaml

This Pull Request adds basic kubernetes configs.
It is separated into 
4  Deployment configs (-api -ws -ui -db)
1 configmap
1 secret config
1 example persistentvolumeclaim
1 Service Config
1 Ingress Config
1 Readme
As of now it should not be used in production, as there is no standard way of exposing the proper paths. The user can choose between  editing the services to use NodePorts or edit the Ingresses to suit its needs. Either way it needs to be reviewed to be set productive.

Apicurio 891 - Kubernetes configurations

---

front-end/studio/src/app/services/template.service.ts

GraphQL integration is using a different way of fetching schema/raw text. 
Current templates do not work. Reverting this change as I could not get this to work without help

chore: revert non functional template

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/info-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/info-section.component.ts

Hi @EricWittmann 
Please don't laugh, i' definitely not a front-end developer. Don't hesitate to give me some feedbacks about this feature.

feat(Editor): Add deprecated support

---

distro/docker-compose/Readme.md

This looks like it is probably outdated. 
The keycloak password is generated in setup.sh [here](https://github.com/Apicurio/apicurio-studio/blob/master/distro/docker-compose/setup.sh#L27) and used in docker-compose [here](https://github.com/Apicurio/apicurio-studio/blob/master/distro/docker-compose/docker-compose.keycloak.yml#L27) - via the .env file [here](https://github.com/Apicurio/apicurio-studio/blob/master/distro/docker-compose/.env.template#L17).

Fix invalid default keycloak password in docker-compose readme

---

distro/docker-compose/docker-compose.microcks.yml

this error message shows up in the logs, when running with mongo 3.3: 
```
com.mongodb.MongoCommandException: Command failed with error 168 (InvalidPipelineOperator): 'Unrecognized expression '$objectToArray'' on server mongo:27017. The full response is {"ok": 0.0, "errmsg": "Unrecognized expression '$objectToArray'", "code": 168, "codeName": "InvalidPipelineOperator"}
```
Upgrading to mongo 3.4.23 fixes that. (same version as currently used in [the docker-compose on the microcks repo](https://github.com/microcks/microcks/blob/master/install/docker-compose/microcks.yml#L6) )

Fix Unrecognized exception '$objectToArray errors

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/DesignsResource.java

This PR addresses #1250
This ensures that microcks URLs starting with https://api... are not parsed incorrectly

fixed microcks url starting with https://api

---

distro/helm/templates/apicurio-studio-ws-deployment.yaml
distro/kubernetes/apicurio-studio-ws-deployment.yaml

The kubernetes and helm example deployments in distro have the same issue as #954. 
This PR adds the env var to the helm chart and the kubernetes yamls so the share for everyone feature works.

added APICURIO_SHARE_FOR_EVERYONE to WS deployment in k8s and helm

---

back-end/hub-codegen/src/main/java/io/apicurio/hub/api/codegen/OpenApi2JaxRs.java
back-end/hub-codegen/src/main/resources/io/apicurio/hub/api/codegen/_OpenApi2JaxRs/pom.xml
back-end/hub-codegen/src/test/java/io/apicurio/hub/api/codegen/OpenApi2JaxRsTest.java
back-end/hub-codegen/src/test/java/io/apicurio/hub/api/codegen/OpenApi2QuarkusTest.java
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-full/generated-api/pom.xml
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-gatewayApi-full/generated-api/pom.xml
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-issue885Api-full/generated-api/pom.xml
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-reactive-full/generated-api/pom.xml
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-registryApi-full/generated-api/pom.xml
back-end/hub-codegen/src/test/resources/OpenApi2JaxRsTest/_expected-registryApi-full/generated-api/src/main/java/org/example/api/ArtifactsResource.java

I added checking if GenerationConfig.isLongInteger is true when generating JavaInterface. if it doesn't check, JavaBean can have long typed fields but the interface take it as integer.

add checking if GenerationConfig.isLongInteger is true when generating JavaInterface

---

front-end/studio/src/app/pages/dashboard/dashboard.page.html

On the Dashboard, "View our Roadmap" was pointing to http://www.apicur.io/roadmap/ that has moved to /studio/roadmap.
I also changed http to https on the two other links.

Fixing roadmap page link

---

front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/servlets/PreviewServlet.java

Hi,
Dereferencing the api seems to fix issue #1113 for me.
Please share your thoughts if this fix is adequate.

Dereference when generating documentation to support imported data types through preview documentation action

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/DesignsResource.java
back-end/hub-api/src/test/java/io/apicurio/hub/api/rest/impl/DesignsResourceTest.java
back-end/hub-api/src/test/java/test/io/apicurio/hub/api/MockEventsService.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/config/HubConfiguration.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/ApicurioEventType.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/EventSink.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/EventsService.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/EventsServiceImpl.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/http/HttpEventSink.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/http/HttpEventSinkConfiguration.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/http/HttpSinkConfiguration.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/integrations/http/HttpSinksConfiguration.java
back-end/hub-core/src/main/java/io/apicurio/hub/core/storage/RollupExecutor.java

Initial implementation of integration events to allow third party apps to easily integrate with apicurio-studio. This provides some interfaces in order to be able to implement different protocols for sending the events. For now only http cloudevents is implemented.
Given the kind of application apicurio-studio is, being able to configure the "firing" of this integrations events in the UI would make a lot of sense. However, because of simplicity, for now configuration is only implemented with env vars and system properties.
So, things remaining for future contributions are:
* configuration in the UI / persistence of the configurations in the DB
* more event protocols, such as kafka
* more event types, at first only design created, updated and deleted are available
* improvements in …

integration events - initial implementation and http cloudevents

---

front-end/studio/src/app/pages/apis/{apiId}/api-detail.page.ts
front-end/studio/src/app/pages/apis/{apiId}/mock/mock.page.html

Now that support of AsyncAPI in Microcks is GA and we starting having a descent editor in Studio, we may enable mocking button for AsyncAPI 2.0 document too.

Enabling Mock with Microcks action for AsyncAPI document too

---

distro/openshift/apicurio-auth-template.yml
distro/openshift/apicurio-postgres-template.yml
distro/openshift/apicurio-standalone-template.yml
distro/openshift/apicurio-template.yml

This PR adds the correct version to the OpenShift templates to work properly, tested this with Openshift 4.6.1 running on AWS.
If any more info is needed, please let me know.

Adding template.openshift.io/v1 to apiVersion fixes #1364

---

front-end/studio/src/app/pages/apis/{apiId}/_components/import-components.wizard.html
front-end/studio/src/app/pages/apis/{apiId}/_components/import-components.wizard.ts

Hello, 
I'm currently looking into ways to use an external component source (namely an apicurio-registry instance) in the studio import wizard and I've come across this inconsistency: the ImportedComponent.from field is optional and the review panel tries to read its name anyway, causing the wizard component to get stuck on the error report.
This PR wraps the "{ic.from} /" part into a conditional block to prevent this.
---
On a side note, I just found this issue and this is what I'm trying to add to a corporate POC
https://github.com/Apicurio/apicurio-registry/issues/752#issuecomment-688859362

Fix member access on undefined (ImportedComponent.from is optional)

---

distro/helm/templates/NOTES.txt
distro/helm/templates/apicurio-studio-api-deployment.yaml
distro/helm/templates/apicurio-studio-db-deployment.yaml
distro/helm/templates/apicurio-studio-ingresses.yaml
distro/helm/templates/apicurio-studio-ui-deployment.yaml
distro/helm/templates/apicurio-studio-ws-deployment.yaml
distro/helm/values.yaml

This pull request represents the changes I had to make to the helm chart to get it working on our cluster.
So I'm making this PR to the upstream in the hopes others find it useful.
(After getting it working, I took all specific values and moved them into the values-yaml so the chart is more generic.)
Changes I did:
- Add `--ignore-db-dir=lost+found` to the mysql arguments, because some persistent volumes come with a lost+found directory
- Add `securityContext: fsGroup: 999` to the mysql deployment because otherwise mysql doesn't have write permissions on its storage volume
- Enable the option of adding extra volumemounts to pods (for us this was needed to mount the public-rootca of our company proxy)
- Change the ingress spec to be able to pass the hostname it's running on from the values …

fix: Improvements and fixes to helm chart

---

distro/docker-compose/config/keycloak/microcks-realm.json.template

Since the docker-compose distro comes without https support having this as a valid redirect uri makes no sense.

Fix microcks docker compose distro realm redirect uri

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/aaimaster.component.ts

Hello, 
When deleting a channel from an AsyncAPI document, a DeletePathCommand is stacked in storage and causes errors on application (can't cast AaiDocument to OasDocument).
This PR changes the created command to DeleteChannelCommand.
--
The renameChannel uses a wrong command too but I think the modal is inactive and no fitting command exists in data-models yet.

Fix command used in AsyncAPI deleteChannel: should be createDeleteChannelCommand

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab/GitLabSourceConnector.java

Fix #1447 
The API for searching for groups was being used when the group did not exist in the linked GitLab, resulting in the project not being displayed.

Fix a condition for list all user Gitlab projects

---

platforms/thorntail/api/Dockerfile
platforms/thorntail/ui/Dockerfile
platforms/thorntail/ws/Dockerfile

I had the following problem :
```
Caused by: java.lang.UnsupportedClassVersionError: Failed to link io/apicurio/studio/fe/servlet/servlets/AngularServlet 
(Module "deployment.apicurio-studio-ui.war" from Service Module Loader): 
io/apicurio/studio/fe/servlet/servlets/AngularServlet has been compiled by a more recent version of the 
Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
We can see that the release has been switched to Java 11 (see verify.yaml)
So in the thorntail images we need java 11
https://github.com/Apicurio/apicurio-studio/blob/master/.github/workflows/release.yaml#L110 
the image used in release.yaml is platforms/thorntail

add java 11 in dockerfile because UnsupportedClassVersionError

---

platforms/quarkus/api/src/main/resources/application.properties
platforms/quarkus/ui/src/main/resources/application.properties

Hello, 
We're using the platforms/quarkus package to test locally (eclipse + wildfly + jboss plugins were a bit too much for us) and this lil miss caused us some errors since quarkus failed initializing the default tenant and only logs the error as debug :)
---
If you're interested in the alternative dev mode it uses some javaenv+sed shenanigans but I pushed it there https://github.com/Apicurio/apicurio-studio/compare/master...DyspC:dev-mode

Fix missing // in default studio.keycloak.url

---

front-end/studio/src/app/pages/apis/{apiId}/api-detail.page.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/api-editor.page.html
front-end/studio/src/app/pages/apis/{apiId}/editor/api-editor.page.ts
pom.xml

This fixes 
- #1561 - The configuration is added
- #1569 - The button appears using the same condition api-detail.page uses
- #1568 - Collaboration is enabled and I've written down my observations in the issue

Asyncapi misc enhancements and yarn configuration

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/payload-tab.component.ts

Move examples for formal AsyncAPI 2.1 structure. It means from:
```yaml
examples:
- laurent:
payload:
id: 'azertyuiop'
fullName: 'Laurent Broudoux'
```
to 
```yaml
examples:
- name: laurent
payload:
id: 'azertyuiop'
fullName: 'Laurent Broudoux'
```

Adapt Studio UI to fit AsyncAPI 2.0 - 2.1 formal examples

---

distro/openshift/apicurio-standalone-template.yml

Changed the Postgresql Image to be a template parameter as it was not deploying correctly with the old values in Openshift 4.7.
Also added a default value for the image tag that resolve to a existent tag that exists in the OpenShift namespace.
it also closes issue #1505

Adjust Postgres Image for Openshift Template Closes #1505

---

platforms/thorntail/api/Dockerfile
platforms/thorntail/api/entrypoint.sh
platforms/thorntail/ui/Dockerfile
platforms/thorntail/ui/entrypoint.sh
platforms/thorntail/ws/Dockerfile
platforms/thorntail/ws/entrypoint.sh

Hello, 
I'm adding a corporate secret management layer to our studio deployment and I came into this issue where extending the image with an entrypoint erases the parent CMD
This change should allow image extension without having to maintain a copypaste of the CMD layer (eg. with another entrypoint ending with `exec /opt/apicurio/entrypoint.sh $@`)

Use entrypoints instead of cmds in thorntail images

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/headers-tab.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/payload-tab.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/shared/schema-type-editor.component.ts

Hello, 
This PR is linked to (but does not depend on) https://github.com/Apicurio/apicurio-data-models/pull/324 and makes sure invalid ref values cannot be selected.
If data types exist in the document
Or else

Parameterize the schema-type-editor for aai message payloads/headers to only see data types

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/response-tab.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/response-tab.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/response-tab.component.ts

Hi,
This fixes an inconsistency between OAS3 and swagger (the swagger editor allowed picking reusable responses but they weren't rendered in design mode)

Handle swagger reusable responses in response-tab

---

distro/helm/Chart.yaml
distro/helm/templates/apicurio-studio-ingresses.yaml
distro/kubernetes/apicurio-studio-ingresses.yaml
distro/kubernetes/apicurio-studio-ui-deployment.yaml

I experienced compatibility issues when trying to deploy Apicurio to Kubernetes using Minikube so I decided to fix them. 
Perhaps you require these to be on an older version and need them to stay as they are, in which case feel free to close this.

Fix templates and configs for Kubernetes and Helm

---

front-end/studio/src/app/pages/apis/{apiId}/editor/aaieditor.component.css

bugfix : the pseudo class ":hover" was missing for the messages section

bugfix : the pseudo class ":hover" was missing for the messages section

---

test/integration/arquillian/pom.xml

This fixes this security issue:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42392.
More info here:
GHSA-h376-j262-vhq6

Update H2 database

---

platforms/quarkus/api/src/main/resources/application.properties
platforms/quarkus/ui/README.md
platforms/quarkus/ui/src/main/resources/application.properties
platforms/quarkus/ws/src/main/resources/application.properties

Some adjustments to allow deployment of Quarkus flavor using Operator:
- Fix exposition port of ws component
- Force OIDC redirect_uri to be https when deployed behing an ingress controller that handles TLS
- Make Keycloak URL config the same that Wildfly falvor so that both can be deployed with Operator

Adjustments to deploy Quarkus flavor with Operator

---

.github/workflows/release.yaml
front-end/studio/README-npm.md
front-end/studio/package.json

This PR moves the NPM package under the `@apicurio` organization. I also noticed some incorrect information in the README which I updated.
Additionally, 7fba69fb9dd2196c4d64b6d0ae50cb9bebe7fc53 hides the email address of our bot account. This should be more secure and leaves it less vulnerable to attacks and spam.

Rename NPM package to '@apicurio/data-models'

---

.github/workflows/release-images.yaml
.github/workflows/release.yaml
.github/workflows/verify.yaml

Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore.
It is highly recommended to migrate workflows from adopt to temurin to
keep receiving software and security updates.

Use Temurin Distribution

---

back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/DesignsResource.java
front-end/studio/src/app/pages/apis/{apiId}/_components/generate-project.wizard.html
pom.xml

Creating as draft as it needs first:
https://github.com/Apicurio/apicurio-codegen/pull/38
The resulting "release" looks as follows:
https://github.com/andreaTP/openapi-cli-gen-ci-poc/releases/tag/0.0.3-SNAPSHOT
Each client `.zip` file contains the sources for the target language/framework as emitted by `openapi-generator`

Add an option to generate a GH action workflow to generate clients from the spec

---

front-end/studio/src/app/components/common/markdown.component.ts

`isEmpty()` function breaks whenever data is a number. Data can be a number when an API definition is imported from JSON/YAML. I believe it can also be a boolean.
The change checks if data has a `trim` function, and runs it if so.
Example property in a schema that triggers the error:
```
"properties": {
"id": {
"type": "integer",
"format": "int64",
"example": 10
},
```

fix: data can be non-string which does not have trim()

---

platforms/quarkus/ws/src/main/resources/application.properties

Hello, 
In answer to issue #2082 : 
The correct spelling of the quarkus property websocket max frame size is : quarkus.websocket.max-frame-size
Official doc : 
Can you check this modification ? 
Happy if it helps :smile:

Fix too large message cause offline

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/path/operation/requestBody-section.component.html

Hello, 
I realised that the request body doesn't have description title as you can see on this screenshot : 
This modification add the "Description" title on this section :

Add request body description title

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_components/common/icon-button.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/properties-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/properties-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/master.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/master.component.ts

Hello, 
This add a button on Properties, Path, Data types and Responses which let the user change the way these are sorted : either alphabetically or according to the source. 
It's the first part of the feature i would like to discuss in the issue #2258

Add sort button

---

distro/docker-compose/.env.template

Hi @carlesarnal ,
In the `.env.example ` file, I switched` '' `to` ""`, `"` to `\"`, and` \ `to` \\` so that it can generate a correct regular expression into `.env`.
This will close #2260 .
Thank you for reviewing it.

Corrected APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP in .env.template

---

platforms/quarkus/ws/src/main/resources/application.properties

- ensures users can edit the source of an api design and save it's contents over a websocket
- related to the fix introduced in https://github.com/Apicurio/apicurio-studio/commit/3f2a21360522ce4869f7f3d3c407b9eebd243fe8, but for mysql
- related to https://github.com/Apicurio/apicurio-studio/issues/1992

fix(mysql): increase websocket max frame size to handle full source editing

---

distro/openshift/apicurio-deployment-configs-template.yml
distro/openshift/apicurio-image-streams-template.yml
distro/openshift/apicurio-routes-template.yml
distro/openshift/apicurio-secrets-template.yml
distro/openshift/apicurio-services-template.yml

Hi @carlesarnal ,
I have changed the `apiVersion` from `v1` to `template.openshift.io/v1` as we discussed before, to avoid an error like this: `no matches for kind "Template" in version "v1”`.
Thanks for reviewing.

Modified templates' version

---

front-end/studio/src/app/editor.module.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition-form.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition-form.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/reference-properties-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition/reference-properties-section.component.ts

Adding a table showing the important informations of the referenced data-type. Would maybe be prettier with tabs to choose between the full file and the table view but I didn't manage to do that.

addition of a properties table for the reference data-types to be able to understand more clearly the data-type.

---

integration-tests/src/test/resources/infra/sql/postgresql.yml

Copy-pasted from https://github.com/Apicurio/apicurio-registry/pull/4510
The old image does not exist anymore.

Use postgresql image based on centos stream

---

back-end/hub-core/src/test/resources/io/apicurio/hub/core/cmd/testExecuteCommands_Rename/__expected.json
front-end/studio/package.json
front-end/studio/src/app/components/common/activity-item.component.ts
front-end/studio/src/app/editor.module.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/aaiadd-tag.component.css
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/aaiadd-tag.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/aaiadd-tag.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/aaimain-form.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/aaitags-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/aaitags-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/info-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/channel/operation/info-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/main/tag-row.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/main/tag-row.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/main/tags-section.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/main/tags-section.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/message-form.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/messagetrait-form.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/messagetrait-form.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/operationtrait-form.component.html
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/operationtrait-form.component.ts
front-end/studio/yarn.lock
pom.xml

fixes #2752
As part of this PR there is also :
* adds tag selection on message nodes
* tag renaming is disabled on all asyncapi nodes. For children nodes it's the same on openapi since inline-array-editor can only add or delete tag. For root node it would require an asyncapi specific RenameTagDefinitionCommand to handle hierarchical renaming on message based and operation based nodes that is not yet available.

fix(asyncapi): handle tags on operation and message based nodes

---

front-end/studio/src/app/pages/apis/{apiId}/editor/_util/model.util.ts

Because of an error in a previous commit to handle allOf, generate example functionality always returns an array even for simple models. This fix returns a simple object as expected by openapi specs and merges models in one object in case of allOf inheritance.
For simple types: 
1. Open an openapi spec and edit a data type
2. Add a property "age" of type number
3. Click "generate" button in example text area
4. Current result:
```json
[
{
"age": 7
}
]
```
Expected result:
```json
{
"age": 7
}
```
With allOf inheritance:
1. Select allOf inheritance type in previous data type
2. add a schema with one property "id" of type number
3. Click "generate" button in example text area
4. Current result:
```json
[
{
"age": 7
},
{
"id": 1
}
]
```
Expected result:
```json
{
"age": 7,
"id": 1
}
```

fix: generate example wrongly returns array of examples

---

front-end/studio/package.json
front-end/studio/src/app/components/common/activity-item.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/dialogs/add-schema.component.ts
front-end/studio/src/app/pages/apis/{apiId}/editor/_components/forms/definition-form.component.ts
front-end/studio/yarn.lock
pom.xml

For asyncapi docs, defining schema with oneOf, allOf or anyOf inheritance isn't working cause required apicurio-data-models commands are missing and `definition-form.component.ts` only supports openapi docs.
This PR upgrades apicurio-data-models to 1.1.30 which brings required commands and adds required modifications to support it.
Marked as draft until  apicurio-data-models 1.1.30 is released.

fix(asyncapi): broken schema inheritance

---

back-end/hub-core/src/main/java/io/apicurio/hub/core/content/AbstractReferenceResolver.java

Linked to https://github.com/Apicurio/apicurio-studio/issues/3030.
An openapi doc can have an external reference on a path containing a template. In that case curly brackets will be present in the url and should be escaped before creating a java `URI` to avoid an exception.

Fix: escape curly brackets that can be found in path items external reference urls
